language: ruby
rvm:
- 2.7.0
branches:
  only:
  - master
install:
- bundle install
script: jekyll build
before_install:
- openssl aes-256-cbc -K $encrypted_ebb8fbb5669e_key -iv $encrypted_ebb8fbb5669e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
atfer_success:
- chmod 600 ~/.ssh/id_rsa
- ssh yan@www.yan-wyb.com -o StrictHostKeyChecking=no 'cd ~/blog/Avalon && bash .travis/deploy.sh && exit'
